version: '3'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
  service-client:
    build: ./eureka-client
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
